### ISSUE TITLE
Tick labels unclear 

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#101]
In some cases the tick label output is not meaningful:

- When displaying a parameter against time for (very?) large time windows the label only shows time, not date, resulting in a long series of "00:00", which is not so meaningful.
- When displaying values on very different scales eg (Latitude(x),Radius(x)) the y-axis ticks are "0" and multiple "000,000". Radius is typically around "800,000", so this is not simply a truncation of values.

**Comment by santilland** [comment]
There were some issues in the tick generation for timestamps which was solved, now values for days, months and years (instead of 00:00) will appear if zooming further out in the time scale.
The radius issue i think could be related to #117. There have been improvements now in the y-scale visualization as the second possible y-axis was implemented. 
I will close this thicker now, if some issue is still prevalent please comment here and i will reopen the issue.
