### ISSUE TITLE
Staging server map tiles not loaded

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#111]
I cannot see the map tiles on the staging environment on firefox 45.0. `GET https://tiles.maps.eox.at/dem/layer.json` returns 200, but I cannot see any content of the file. On chrome and firefox 50.0(Nightly) it works fine, and it works fine on production on firefox 45.0.
![screenshot from 2016-07-27 19 41 50](https://cloud.githubusercontent.com/assets/17086561/17187275/de372c76-5438-11e6-8669-1b7959c89f3c.png)

**Comment by pacesm** [comment]
I confirm this issue. The browser logs tells:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://tiles.maps.eox.at/dem/layer.json. (Reason: CORS header 'Access-Control-Allow-Origin' does not match 'http://127.0.0.1:8300').
```

This looks like misconfiguration.

**Comment by pacesm** [comment]
The problem seems to be caused by switching between different deployment.
The browser remembers URL of the previous client in the CORS header and refuses loading of the maps for the new one.

As a temporary workaround I suggest to clear the browser cache when switching between deployments.

Side note: This issue is not specific to `staging` and it is definitely not related to #110. It must have been there already before.

**Comment by Schpidi** [comment]
I'm looking into this on the side of the maps service. Those CORS headers are killing me...

**Comment by Schpidi** [comment]
Apparently the solution is to set the `Vary` response header to `Origin` to tell the browser to cache different versions for different domains. This is now applied to our maps service.
Already existing caches need to be cleared first.

**Comment by pacesm** [comment]
@miktoki The problem should be resolved now. Can you please check it and close the ticket.
But before you do so, please,  make sure you clear the cache of your browser.

Brief info about the issue:
- The problem was in the external service providing the map layers to the client.
- The issue affected all instances and not only staging but also production.
- There is no regression in the VirES server/client SW.
- There is no relation to the pending #110

**Comment by miktoki** [comment]
Yes,

The issue seems to be solved now. I then believe you can go ahead with the production deployment.
