### ISSUE TITLE
Dynamic range calculation for models

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#116]
Selecting a magnetic model in the layers list, the initial scale range selected by VirES for the "Total field intensity" parameter is 27000-50000 (this is valid also for custom models).

Changing the coefficients range and/or height values, the scale range is automatically updated. E.g., for IGRF12, changing the coefficients range to 13-20 and height to 0 the scale range for the total field intensity is set to 2-30.

Changing the values back to the initial (default) ones (i.e. -1, -1 and 450), the scale range is not set to the original 27000-50000 (e.g., for IGRF12, is set to 15000-55000). This happens also leaving the coefficients and height unchanged but changing the parameter and then going back to the "Total field intensity".

It seems that the initial range 27000-50000 is a default range. Shouldn't it be automatically calculated as soon as the specific model's layer is selected?

**Comment by pacesm** [comment]
related to issue #70

**Comment by santilland** [comment]
Hello Imar,
as you correctly observed the initial values are taken from a initial (default) value in the settings It is also implemented that if, for whatever reason, there is an issue with the calculation of the values, the default ones from the settings would be taken showing a warning message.
In order to use the calculation as little as possible it is only implemented to be used when changing the settings for the model calculation, doing it before each request (as would be one way to make sure also for the first one it is done) would not be to ideal from my point of view.
I think our best solution would be to adapt the default values in the settings to match the ones calculated, this way changing back to "-1" would set the values back to the same values as before. Not creating a confusion to the user.
The range for all three models for total field intensity is 15000 to 55000, i would then set this value also as default for the Swarm total field intensity parameter to allow easier comparison.
Do you agree with this approach?

**Comment by lmar76** [comment]
Hello Daniel,

Just for clarification. You suggested to continue to use an initial (updated) default range. On the other hand, instead of using these default values, would it be too expensive in terms of computation to calculate this range as soon as the layer is selected? With this second option you could have always “the best” range for every layer you select. What do you think about?

Thanks,

Luca

**Comment by santilland** [comment]
I looked at the values for all models and quite some times (into the past) and they all have the range 15000 to 55000. Of course i do some "rounding" in order to not have 15123.12312351 to 54354.12645 as range limits, which makes the range really uncomfortable to read.
So i don't actually see the need to re-calculate the values, as we know that this is the result of the calculation and is a nice and simple solution which also reduces the request load to the server, so i see it as a win/win.

**Comment by lmar76** [comment]
Ok Daniel, I agree.

**Comment by santilland** [comment]
The discussed solution is now prepared in staging and can be tested. I will close the ticket now. If there is still anything that needs clarification or is not working as expected we can reopen the issue.
