### ISSUE TITLE
Custom download parameters - removal and reordering

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#139]
In the download manager window, selecting the "Custom download parameters" checkbox, the default parameters Latitude, Longitude, Timestamp, Radius appear. It is possible to remove them only clicking with the mouse on the text field and pressing the backspace button.

![Fig1](https://cloud.githubusercontent.com/assets/20207042/18874946/11ccdf70-84c4-11e6-971f-8d6c00ea2c04.png)

On the contrary, the other parameters have a remove ("x") button to remove them from the list:

![Fig2](https://cloud.githubusercontent.com/assets/20207042/18875069/85b6646a-84c4-11e6-83c4-ac3eec97035a.png)

Moreover, it is not possible to reorder the selected parameters. This has an impact on the columns order in the downloaded CSV data.

**Comment by santilland** [comment]
Ok, so for now (locally) i changed it so that the minimum required set (which is lat,lon,rad,t) can no longer be removed.
For reordering we would need to think what we want to do, either we use some kind of alphabetical order automatically or we a actually allow the user to pick the order he wants to have as it is right now. He can remove and readd elements to change the order if really necessary. Maybe if we allow ordering we could (as helper tool) introduce ordering by dragging, but i think to make that work correctly we would need some time.

**Comment by santilland** [comment]
Pushed to production, if any comments this can be reopened
