### ISSUE TITLE
Download manager - issue on custom time selection

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#175]
Issue observed on v1.2

The following settings have been selected for the download of MAGA_LR_1B data:
- start date: 01/03/2016
- end date: 01/03/2016
- custom time selection: **10:00:00.000 - 12:00:00.000**

The following two files have been downloaded:
- SW_OPER_MAGA_LR_1B_20160301T**100000**_20160301T**115959**_Filtered.cdf
- SW_OPER_MAGA_LR_1B_20160301T**100000**_20160301T**115959**_Filtered.csv

The two files contain data in the interval: **01/03/2016 10:00:00 - 01/03/2016 11:59:59**

The DATA_TIMESPAN parameter in the CDF file has the following value:

['2016-03-01T**10:00:00Z**/2016-03-01T**12:00:00Z**']

The data content and filename should match the selected custom time span, i.e include also the last sample at 12:00:00

**Comment by santilland** [comment]
This issue comes from the previously discussed ticket #154 where in order to include all data of the last second we actually request up to (excluding) 00 (i.e. to 999ms - to "infinite" .9) and then remove one second in the naming of the seconds, so that we are equal to the PDGS naming convention.
I think it should be possible to add 1 millisecond to the time, then the naming should be correct.
Still i am not sure if this would be the best approach, as at some point in the future there could be some data at the first milisecond and we would have the issue we tried to avoid in the previous ticket.

**Comment by lmar76** [comment]
Just for clarification, in [#154](https://github.com/ESA-VirES/WebClient-Framework/issues/154), as far as I understood, you modified the query (begin_date <= t < end_date) with end_date = original_end_date + ".999" (where original_end_date = date + "23:59:59") and truncating the end_date in the file to the last second (i.e. 59). Is it correct?

If we use the same approach but adding 1 millisecond we would have end_date = 01/03/2016 12:00:00.001 requesting data in the interval 01/03/2016 10:00:00 <= t < 01/03/2016 12:00:00.001 and the file will have the end_date truncated to the last second (i.e. "00"). Correct?

If we will have data at the first millisecond (".001") this sample will be excluded but it is outside the original query interval. Is it correct?

**Comment by pacesm** [comment]
@lmar76 
Please note that the server-side WPS process takes the full UTC time stamp. I.e., if you selected data from 2016-03-01 to 2016-03-02 the web client sends requests for data
2016-03-01T00:00:00.000Z  <= t  < 2016-03-03T00:00:00.000Z .

Originally selection was made as 
2016-03-01T00:00:00.000Z  <= t  <= 2016-03-02T23:59:59.000Z 
which excluded all samples 2016-03-02T23:59:59.000Z < t < 2016-03-03T00:00:00.000Z .

That is also the reason why you see the the time span ['2016-03-01T10:00:00Z/2016-03-01T12:00:00Z'].

**Comment by santilland** [comment]
In #154 we decided that the interface should use for the query begin_date <= t < end_date. This means that in order to get all measurements of the "last second" we decided to use as end date 00:00:00.000 of the next day, which thus includes everything up to 000ms without including 000ms. But in order to have the same naming es the PDGS products we reduce the query time by one second.
So rethinking this, adding one millisecond does not really solve the issue. 
I think reducing the second in the label does make sense as in the query the measurement value for 12:00:00.000 will not be included.
If the naming should be equal to the query we should revert or implement both options:
1) begin_date <= t < end_date for "complete" products
2) begin_date <= t <= end_date for "custom" times
I personally don't think it is a good idea to have two different query methods.

**Comment by pacesm** [comment]
Note that we can subtract 1us (our time resolution) form the upper bound of the upper bound of the CDF DATA_TIMESPAN.

Please do not implement ad-hoc time selection for the custom time. This would bring only troubles.

**Comment by lmar76** [comment]
Given that the maximum resolution is 1us, maybe we could use the same query interval t0 <= t <= t1 in both cases:
- Default (dates only): t0 = start_day 00:00:00.000000, t1 = end_day 23:59:59.999999, the t1 value in the filename is truncated to the last second (i.e. remove fractions of a second).
- Custom time selection: change the time format to hh:mm:ss.ffffff (i.e. let the user to indicate microseconds) and use the t0 and t1 specified by the user. Also in this case, t1 value in the filename is truncated to the last second.

**Comment by santilland** [comment]
I also consider this to be an acceptable solution. It is now implemented in the current deployment.
I am closing this ticket, if there is any further feedback please comment here.
