### ISSUE TITLE
Dst scatterplot: misalignment between staging and operational instances (v1.2)

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#180]
The following Dst scatterplot (day 01/03/2016) have been downloaded from operational and staging instances:

**Operational**
![dst_20160301_op](https://cloud.githubusercontent.com/assets/20207042/22424725/21150caa-e6f8-11e6-9240-9b332065a561.png)

**Staging**
![dst_20160301_staging](https://cloud.githubusercontent.com/assets/20207042/22424730/25026b82-e6f8-11e6-96f5-36dd469e1fa1.png)

Can you please investigate?

**Comment by eox-cs1** [comment]
Staging is intended to demonstrate features, design etc. Datasets on the staging instances are not updated automatically, because the data-directory is mounted via NFS which doesn't allow inotify.  If there is a need (e.g. when new datasets are added) datasets update are performed manually.  
If you need new Dst/Kp on staging (or testing) then please let me know.  ciao

**Comment by lmar76** [comment]
I understand your point, but sometime, for regression testing, I need to compare the results of a new software release with the results (of the same scenario) obtained with a previous release. Usually I execute queries in the time period March 2016 - April 2016. Could it be possible to align at least this period?

**Comment by eox-cs1** [comment]
Staging is now updated as per today ~ 17:50, for Datasets as well as Aux-Data (DST & KP). 
The Aux-Data is now configured to get updates every 4h (concurrently with production). 
Datasets will only be updates manually on request.

**Comment by santilland** [comment]
If time interval looked at for comparison is stable this issue is solved, closing ticket now. If there is some issue during check please comment here.
