### ISSUE TITLE
Error while selecting all products and satellite

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#186]
Issue detected on v2.0 (staging).

While selecting all the available all data and satellites (see first screenshot) an error occurred (see second screenshots).

![image](https://cloud.githubusercontent.com/assets/20207042/24036436/d1f9ed4a-0af9-11e7-86b1-b17fe88c9bbd.png)

![image](https://cloud.githubusercontent.com/assets/20207042/24036422/c27c18d4-0af9-11e7-8aea-9ae3b2bedb88.png)

**Comment by santilland** [comment]
Thanks for the info, the issue comes from EEF not having data for Charlie, so when trying to "merge" any product with EEF with Charlie selected this error appears.
The same happens when trying to merge FAC data "Non S/C" with another product.

One consideration of how to approach this would be, as soon as EEF is activated to disable the Charlie checkbox and when any other dataset then FAC is selected to disable "Non S/C" checkbox.
Im just not sure if this would be easy to understand by the user.

**Comment by santilland** [comment]
Current solution removes "pairs" which are not possible in request. It is difficult for the user to understand why some if the data is not being shown.
The ideal solution would be to show all data that has been selected. We need to reconsider how we combine and show the data to have this effect.

**Comment by miktoki** [comment]
If the ideal solution is not possible, I think the GUI should make it clear to the user, either by refusing to add the new product before old is removed, or by removing the other product causing the conflict. 

Either way, a notification should appear to explain what is going on, and the tick marks in the layers widget should always reflect what is currently being displayed.

**Comment by santilland** [comment]
The approach of how data is requested and served was adapted a little. Now it is possible to request "impossible" combinations, such as Alpha and NSC for MAG and FAC. As MAG has no NSC data the request will return null (empty) values for MAG (e.g. F parameter) NSC without errors, still showing the corresponding FAC data.
I will close this ticket as there is no longer an error and the implemented behavior is as expected.
If there any other comments related to this please feel free to add them here.
