### ISSUE TITLE
Visualization of time scale on X-axis

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#249]
Issue detected on v2.2 (staging)..

As indicated in the changelog (last bullet of "Plotting (Analytics viewer) tool reworked and updated"):

>The visualization of time on the x axis has been reworked to show better tick-marks as well as always showing complete dates for start and end ticks

The complete date is visible at the second and penultimate ticks and not at start/end ticks.

The time format of the "minor" ticks is 12-hour (wile the major ticks label have a 24-hours format). In some cases (e.g. increasing the zoom level) the AM/PM indication disappears and the user must refer to the complete date string at second tick to understand if the time is before mid day or after mid day (see image below).

![download](https://user-images.githubusercontent.com/20207042/40123796-5304ae30-5927-11e8-8156-985c19f163df.png)

**Comment by santilland** [comment]
With the text i meant showing a complete tick for a start and for an end value, not that these ticks are located at the first and last tick. It can be changed but it often is cut because it goes out of the plot boundaries. The boundaries could be increased but would make the plot smaller.
When presented during the EGU there was no negative comment about positioning.
Please let me know what you think is the best approach.
I agree that the 12h vs 24h difference is not ideal, ill check what can be done in that respect.

**Comment by lmar76** [comment]
Agreed.
