### ISSUE TITLE
'time selection outside the model validity' warning not displayed for the new Swarm SHA L2 models.

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#263]
The recently added Swarm L2 SHA models, like the older models, are limited by the validity period.
A warning should be displayed when the time selection exceeds this validity period, just like it is done for the older models.

**Comment by pacesm** [comment]
The issue seems to be more complicated then I thought.

![image](https://user-images.githubusercontent.com/4050019/42218787-fbad82c4-7ec9-11e8-9cda-4e4678c3931f.png)

First, I  turned out the model validity used by the warning messages does not come from the same source as the validity displayed by the time-slider. The fist is hard coded in the client configuration while the latter is queried dynamically from the server.

**This is clearly a design flaw which needs to be fixed. The validity retrieved from the server shall be the only value used by the client.**

It was not a big problem until the models were updated manually but since we changed to automated model updates the model validity may change at any time.

As temporary solution the hard-coded validity should be updated for less frequently updated models and disabled for the daily updated MMA_SHA_2F model.

Please also note that the validity of the MIO models is constrained by the availability of the F10.7 index values.

**Comment by pacesm** [comment]
Please note the model validity is stored together with the product definitions in the browser local storage. That means updating the configuration is not enough to update the validity warning. The client must be reset (i.e., press the reset button) in order to bring these changes into effect.

**Comment by lmar76** [comment]
Tests have been repeated after cleaning the browser's cache. The warnings are visualized (with the exception of MMA_SHA_2F models) and they are aligned to the model's validity (crosschecked with availability displayed on time bar).

For MIO models it could happen that the time bar indicates (i.e. with the availability line) that the model is valid in the selected time range (e.g. 11-13/06/2018) but the model is not represented on the globe (see screenshot). I guess that this is due to the missing F10.7 index but I can't confirm it because the scatterplot is not displayed (due to the limited data on staging server). If this is the cause of the issue, I propose to improve the warning message indicating that F10.7 is not available and the model can't be visualized (this to avoid confusion to the user). It could be very useful to represent the F10.7 also on the time bar (as already done for Kp and Dst).

![image](https://user-images.githubusercontent.com/20207042/42280026-de137634-7f9f-11e8-9246-3bc4ba5643a1.png)

**Comment by pacesm** [comment]
@lmar76
> It could be very useful to represent the F10.7 also on the time bar (as already done for Kp and Dst).
please see https://github.com/ESA-VirES/WebClient-Framework/pull/266 can be added in no time

**Comment by pacesm** [comment]
@lmar76 
> The warnings are visualized (with the exception of MMA_SHA_2F models) ...

The MMA_SHA_2F is updated daily and therefore the hard-coded limit would not work.

> For MIO models it could happen that the time bar indicates (i.e. with the availability line) that the model is valid in the selected time range (e.g. 11-13/06/2018) but the model is not represented on the globe (see screenshot). I guess that this is due to the missing F10.7 index but I can't confirm it because the scatterplot is not displayed (due to the limited data on staging server). If this is the cause of the issue, I propose to improve the warning message indicating that F10.7 is not available and the model can't be visualized (this to avoid confusion to the user).

It is technically possible but this would require some effort to change the client.

> It could be very useful to represent the F10.7 also on the time bar (as already done for Kp and Dst).

already deployed

**Comment by lmar76** [comment]
Dear Martin, I think that now we really need what you proposed:

> The validity retrieved from the server shall be the only value used by the client.

because we are seeing this discrepancy (between the warning message and the availability on the time bar) also MCO_SHA_2F: the waning message reports an end of validity equal to 2017-01-01T00:00:00Z but the availability on the time bar ends on 31/12/2017.

After internal discussion we would like that also the model representation on the globe is visualized only if the selected time interval is inside the time validity of the model (i.e. like the other products).

**Comment by lmar76** [comment]
In addition we would like also a review of the warning message. It should indicate the correct validity time of the interval but also that the residual is not calculated due to the fact that the time interval is outside the model's validity interval.

**Comment by pacesm** [comment]
@Imar76 Thanks for bringing this up.

The way the client handles the model validity has to reviewed and fixed/improved. I agree. I will raise the priority of this ticket.

**Comment by pacesm** [comment]
Fixed. Already deployed in production.
