### ISSUE TITLE
MLI and MIO models validity on the time bar not always visible

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#267]
Issue detected on operational and staging servers (v2.2) with Chrome browser.

The MLI and MIO availability (i.e. the line) on the time bar is not always visible and it depends on the zoom level:
1. Select a time window satisfying the MLI/MIO model's validity (e.g. 01/01/2016, all day).
2. Select the model in the layers list (e.g. MLI_SHA_2C) -> the model is represented on the globe, the plot F_*residual* is visualized but **the availability line of the model is not displayed on the time bar**, only the MAG LR one is visible:

![image](https://user-images.githubusercontent.com/20207042/42313001-f0c52f1e-8041-11e8-809d-4cae76e6fda2.png)

3. Decrease the zoom level on the time bar -> the model's availability line becomes visible:

![image](https://user-images.githubusercontent.com/20207042/42313167-5884dd70-8042-11e8-9f13-74a38fc4a979.png)

4. Increase again the zoom level on the time bar -> the line disappears:

![image](https://user-images.githubusercontent.com/20207042/42313306-b3002d2c-8042-11e8-843c-a3ffe9fb7c58.png)

The issue has been detected only with MLI and MIO models.

**Comment by pacesm** [comment]
I confirm that this issue is still present in the current (v.2.2.3) client.

I did not observe this behavior in Firefox and it seems to be Chrome specific (tried with v71.0). It seems the clipping done by the rendered is the culprit. The issue is not limited to the "infinite" MLI and MCO models but it can happen to any model when the validity bounds get too far away with respect to the viewed time interval.

**Comment by pacesm** [comment]
fix already deployed on staging

**Comment by lmar76** [comment]
Tested.
