### ISSUE TITLE
CSV vs CDF discrepancies

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#282]
I have compared some VirES CDF/CSV products to the corresponding Swarm official ones and I have found some "small" differences between the values included in the VirES CSV and the corresponding values in the official CDF. These differences have been found only in the variables having floating point values and they seem to be related to different rounding and/or number of decimal digits.

In attachment you can find an example of this comparison executed on MAGA_LR_1B products ([MAGA_LR_1B.zip](https://github.com/ESA-VirES/WebClient-Framework/files/2832115/MAGA_LR_1B.zip)) but I have found the same issue also in the other products.

I think that these differences should be analysed by DISC to verify that they o not exceed any tolerance.

**Comment by pacesm** [comment]
@lmar76 
CSV is a text data format and the floating point values cannot be identical because of the text decimal representation. The precision of the floating point values is set to 9 significant digits (`%.9g`).

If you think the precision is not sufficient we can add more digits at a cost of the file size.

CDF is a binary data format and the floating values are stored without any loss of precision.

**Comment by lmar76** [comment]
@pacesm Thank you for the explanation. I don't think to be the right person to answer this question. I think it is better to ask DISC (e.g. Nils).

**Comment by pacesm** [comment]
@lmar76 Understood. I'll raise this question in DISC.

**Comment by pacesm** [comment]
TODO: add a note to FAQ about precision of FP values in the CSV data format.

**Comment by pacesm** [comment]
A note about the CSV precision was added to FAQ.

See: https://github.com/ESA-VirES/VirES-Server/blob/staging/eoxs_allauth/eoxs_allauth/templates/account/faq.html#L167

**Comment by pacesm** [comment]
Done. The updated FAQ were already deployed in production.
