### ISSUE TITLE
Add tooltip for magnetic model (enhancement)

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#293]
Currently, pointing the mouse over the product's availability line on the time bar, a tooltip appears indicating the corresponding filename. Since some of the magnetic models are downloaded from the same Swarm FTP server, it could be useful to indicate a tooltip also for these file names.

**Comment by pacesm** [comment]
OK, that makes sense. Perhaps, we could include in VIR-240.

**Comment by pacesm** [comment]
FYI, since we changed to the composed model in v2.3.0, there might be more than one model file at a time.

The validity of the composed model shown on the time slider is an intersection of the validates of the contributing models it might be also good to indicate what the actual model composition is (model expression).

**Comment by lubojr** [comment]
An enhancement has just been deployed to staging. Used model source files can be seen after clicking the info button while choosing model components in Layer settings. An info button has also been added to the analytics window, which shows the source files of used products.

**Comment by lmar76** [comment]
Tested

**Comment by pacesm** [comment]
This feature has been already deployed to staging and it is scheduled for the 3.0.0 release. See https://github.com/ESA-VirES/WebClient-Framework/milestone/2

I am closing the ticket.
