### ISSUE TITLE
MLT parameter on secondary Y-axis not visible

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#309]
The following plot has been visualized on the operational v2.2.3: F vs Timestamp + MLT vs Timestamp

![image](https://user-images.githubusercontent.com/20207042/54192921-4ba12000-44b9-11e9-9d4f-1e8d5b34ef4b.png)

A tentative to reproduce the same plot on v2.3.0 (staging) has been done but the MLT is not visible:

![image](https://user-images.githubusercontent.com/20207042/54193034-8d31cb00-44b9-11e9-9bb3-38307c470e32.png)

**Comment by pacesm** [comment]
This issue is cased but a current limitation of the plotting library which does not allow mixing cyclic and regular y-axes. As a mitigation we disabled the cyclic axis for seconds y-axis (MLT) and the plots is possible like in the previous version v2.2.3.

The fix has been already deployed on testing.

**Comment by lmar76** [comment]
Ok, tested.

**Comment by lmar76** [comment]
It works also on the operational platform. I think it can be closed.

**Comment by pacesm** [comment]
OK, I am closing the ticket.
