### ISSUE TITLE
Overplotting centers on new data

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#44]
When overplotting a parameter on top of another one the first parameter falls outside the plot.

![8 - overplotting](https://cloud.githubusercontent.com/assets/17086561/14453725/c19b560a-0096-11e6-8457-33eb3a3d750c.png)

This becomes even worse when the second parameter has a completely different scale eg. F and latitude:

![analytics-3](https://cloud.githubusercontent.com/assets/17086561/14453747/e95a3c10-0096-11e6-9b1b-143e04f62946.png)

Because the y-axis is rescaled(and cannot be adjusted other than through zooming in) it would take long time to pan back to F, and then the y-axis would still only span over  ~200 units, while F can span ~40000 nT.

When overplotting: can the initial zoom level include both/all parameters - and additionally: is there some alternative way of rescaling the y-axis?

On a side note - the x-label("Latitude") in the (F(lat), lat(lat))-plot is overplotted by the gridline, making it difficult to read.

**Comment by santilland** [comment]
Updated analytics plot to show  "maximum" domain of both/all data. For future developments we could think about a more intelligent creation of additional axis with different domains depending on the size difference. I created a separate ticket to discuss ideas (#46)
Also created another ticket for the label overplotting issue (#45) 
I am closing this issues as the asked zoom level (/domain) is now set to show domain of all selected parameters (since commit 9b00033208efff1f500cf16af0213d12a9d4b4f5).
Please report any issues or questions still remaining and I'll gladly re-open the ticket.
