### ISSUE TITLE
Safari - loading after download 

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#63]
After downloading data using safari the mouse continues to indicate that the system is loading. 

The system is also experienced as significantly slower until system is restarted.

**Comment by santilland** [comment]
This type of filtered download is a little temporary and will be replaced with an asynchronous functionality. For now i have moved the initialization of the download to a new tab, instead of internally inside of a hidden iframe. This should hopefully solve issues with not a good interaction with the client as tabs are usually fairly independent. When the download starts the new tab should close automatically if there is an error a website with information on the error should be visible.
I think this is a good solution for now and will also do some tests on safari and report back. Please let me know if this approach works also on your system.

**Comment by santilland** [comment]
Changed the behavior again in commit 75d52ebd1a702c71e91e2b8c96359d0876de1cdd
Loading indicator issue should be solved now, the behavior still opens a new tab. When download finishes it is closed (only in some browsers, not safari).
I think until we make use of asynchronous functionality this will be the only workaround that offers a solution.

**Comment by santilland** [comment]
Through the use of asynchronour processing to create the download and making use of the standard file download method of the browser this issue is no longer applicable. I will close it now, if there is any other comment please feel free to do so.
