### ISSUE TITLE
Initial range of colorbar based on data range

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#70]
Colorbar does not change based on coefficient range, this currently has to be done manually, which can be tedious, and often involves some guesswork.

It was suggested to use a rounded value of the minimum and maximum values, or alternatively, a fraction of the root-mean-square of the data (rms could be esp. useful for 0-centered data which use diverging colormaps).

**Comment by miktoki** [comment]
Another thought to circumvent having to get the global temporal maximum and minimum values would be to have a checkbox "custom range" in the settings. When this would be checked, one would have the current behaviour. When unchecked, make the system figure out only the global spacial extremal values(which are not so difficult to compute as you already have computed the values from the spherical harmonics). 

When changing time range or coefficients, one could just have a callback function recompute the max and min values and adjust the domain used in coloring accordingly. To then further tweak the colours to ones needs one could then just check the box again, allowing for a custom domain for the colors.

**Comment by pacesm** [comment]
@miktoki: It is slightly more complicated. The models are requested via the WMS protocol and Cesium requests the displayed results by tiles. The additional tiles are requested when you zoom-in.

Each tile-request is isolated and it is not possible to easily get the global extremes (or any other global parameter). The global range bounds need to be known beforehand and sent with every tile request.

I guess we would need to implement an additional WPS query estimating the optimal range-bounds before the WMS calls are made.

**Comment by miktoki** [comment]
@pacesm I am not familiar with the WMS protocol or in general with server communication), but to make sure I understand:

At some point(s) you compute the model values over the globe using the coefficients on the server side. This is information is then used to generate the tile(s) with Cesium, which then is passed to the client. Then the map is updated only interacting with the service?

As far as I can see one would need the extremal values before using Cesium. The only time where one would want to change the colorbar range is when (1) a  user wants to visualize a model parameter, (2) A user manually changes the colorbar range or (3) a user changes coefficient range. I do not think changing the colorbar is necessary when zooming.

Currently (1) is predefined statically for each parameter AFAIU. (2) works fine, and I assume this is purely a client-side thing (or something that is handled as part of requesting tiles?), while in (3) you would have to recompute the model values, effectively similar to (1), but parameters statically set typically do not fit with the range.

If you have to recompute the model values, I presume some interaction with the server is required? Is this what you mean by the additional WPS query, that you store extremal values somewhere to be used when requesting tiles?

Is this very complicated?(once again, I am not too familiar with the technology)

**Comment by pacesm** [comment]
@miktoki 

> At some point(s) you compute the model values over the globe using the coefficients on the server side. This is information is then used to generate the tile(s) with Cesium, which then is passed to the client. Then the map is updated only interacting with the service?

Not quite. The Cesium internally divides the global coverage to a pyramid of tiles and requests the tiles it needs  individually from the server based on the required zoom level and displayed area. Each tile request is one separated HTTP (WMS - Web Map Service) request (an image), i.e., the server evaluates small subsets and does not know the full extent of the covered area. 

Each tile is an RGB image with already applied color map, i.e., when you change the range extent or the color-map a new image must be requested from the server.

> As far as I can see one would need the extremal values before using Cesium.
>  I do not think changing the colorbar is necessary when zooming.

You are right we need to pass the range extent (as well as the model coeff. range) to Cesium which handles the WMS layer rendering and these parameters stay constant for any zoom level.

> The only time where one would want to change the colorbar range is when 
> (1) a  user wants to visualize a model parameter, 
> (2) A user manually changes the colorbar range or 
> (3) a user changes coefficient range.

When the model is displayed first time (1) or the range extent (2) or coeff. range (3) are changed by the user, the Cesium is requested to re-render the layer for the new parameters.

> Currently (1) is predefined statically for each parameter AFAIU.

Correct and that works fine as long as we do not cut off the most significant SH coefficients and the values start to be too low.

> (2) works fine, and I assume this is purely a client-side thing (or something that is handled as part of requesting tiles?),

Nope, we have not come that far yet. As I said any range extent change triggers a new server requests. Although, what you have described is considered for the evolution and Daniel already successfully used this approach in another project.

> while in (3) you would have to recompute the model values, effectively similar to (1), but parameters statically set typically do not fit with the range.

In principle, there is no difference between (1), (2) and (3) right now. All trigger server-side rendering.

> If you have to recompute the model values, I presume some interaction with the server is required?
> Is this what you mean by the additional WPS query, that you store extremal values somewhere to be used when requesting tiles?
> Is this very complicated?(once again, I am not too familiar with the technology)

Well, the issue is that we need the global min. and max. values of any coeff. range which we cannot get right now because:

1. we do not have the actual model values in the client (we have only the RBG images) and
2. on the server we see only local subsets of the model values.

There are two possible solution each having its pros and cons:

1. A complicated one: to get the model values from the server to the client and perform the range scaling / color-map operations there based on the actual min. and max. values (basically what you have described in you comment).
2. An easy one: implement a new WPS process returning the global min. and max. values to set a reasonable range extent for the given coeff. range before setting up the Cesuim WMS layer. These range bounds do not need to be very precise and a fast estimate could work.

I hope I made it a bit clearer.

**Comment by santilland** [comment]
As described by pacesm for service version 1.1 the second option - precalculation of global min max of the model - has been introduced allowing to dynamically and automatically set the range for the color scale when changing model parameters.
Marking this issue as closed. If there is any further feedback please feel free to comment and we will reopen the ticket to continue the discussion.
